#!/bin/bash
DIR=/var/www/app
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/usr/local/lib/node_modules
NODE=/usr/local/bin/node

test -x $NODE || exit 0

function start_app {
    NODE_ENV=production nohup "$NODE" "$DIR/app.js" 1>>"$DIR/logs/app.log" 2>&1 &
    echo $! > "$DIR/pids/app.pid"
    echo "App started ..."
}

function stop_app {
    kill `cat $DIR/pids/app.pid`
    echo "App stopped"
}
    
case $1 in
    start)
        start_app ;;
    stop)
        stop_app ;;
    restart)
       stop_app
       start_app
       ;;                                                                                  
    *)
        echo "usage: app {start|stop|restart}" ;;
        esac
        exit 0

